version: "3.4"

services:
  api:
    image: aschi2403/docker-wpf-exercise
    # build:
    #   context: .
    #   dockerfile: API/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=sql.data;Database=CarBookings;User Id=sa; Password=Thisisapassword@123;"
    depends_on:
      - sql.data
    ports:
      - 8080:80
    links: 
      - sql.data
  sql.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Thisisapassword@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"